version: "3"
services:
  mysql:
    image: mysql:8.0.23
    # user: "1000:1000"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: persondb
    volumes:
      - ./scripts/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql

  jupyter:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888/tcp"
      - "4040:4040/tcp"
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./data/jupyter/work:/home/$USER/work
      - ./data/jupyter/libs:/home/$USER/libs

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080/tcp"
    deploy:
      restart_policy:
        condition: on-failure
