version: "3"
services:
  jupyter:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888/tcp"
      - "4040:4040/tcp"
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./notebooks:/home/$USER/work
      - ./libs:/home/$USER/libs
